version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: test_db
    volumes:
      - "db.data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    tty: true

volumes:
  db.data:
